- Assets/Scenes/Board.unity
- Assets/Scenes/Board.unity.meta
- ProjectSettings/SceneTemplateSettings.json
> 5 
Tile, Board 씬에 기본 오브젝트로 만들어서 배치
board 씬 제작 및 타일, 플레이어 배치
> [design] Board 씬 제작

- Assets/Prefabs.meta
- Assets/Prefabs/Prototype.meta
- Assets/Prefabs/Prototype/Tile.prefab
- Assets/Prefabs/Prototype/Tile.prefab.meta
- Assets/Scenes/Board.unity
- Assets/Scripts.meta
- Assets/Scripts/Board.cs
- Assets/Scripts/Board.cs.meta
- Assets/Scripts/Player.cs
- Assets/Scripts/Player.cs.meta
- Assets/Scripts/Tile.cs
- Assets/Scripts/Tile.cs.meta
> #10 
> - 기본 폴더(prefabs, scripts) 생성
> - 보드 칸, 판, 플레이어 스크립트 생성
> - 타일 프리팹화 및 배치
> [feat] 폴더 및 보드 칸, 판 생성

- Assets/Scripts/Player.cs
> #13 Player 스크립트 작성
> 플레이어가 가져야 할 기본 속성(변수)들을 작성했습니다. 
> Move의 매개변수 이름 diceValue가 좋을까요 steps가 좋을까요? 다른 의견 있다면 남겨주시면 감사합니다.
> [feat] 플레이어 기본 속성

- Assets/Scripts/BoardManager.cs
- Assets/Scripts/BoardManager.cs.meta
> ex) #12 
> - 필요한 변수, 함수 작성
> - 함수 내부는 merge후 작업 예정
> While문으로 턴 관리하는 거 괜찮을까요?
> [feat] BoardGameManager.cs 틀 제작

- Assets/InputSystem_Actions.inputactions
- Assets/ScriptableObject.meta
- Assets/ScriptableObject/InputManager.asset
- Assets/ScriptableObject/InputManager.asset.meta
- Assets/ScriptableObject/InputManagerSO.cs
- Assets/ScriptableObject/InputManagerSO.cs.meta
> #14
> 유저 입력을 처리해주는 Input Manager 제작
입력은 Confirm 버튼 하나이고 현재 Space 키에 바인딩 되어있습니다.
키가 눌러졌을때, 눌렀을 때, 뗐을 때 3가지 이벤트 구현되어있습니다.
(ButtonDown, Button, ButtonUp)
ScriptableObject/InputManager 에셋을 레퍼런스하시고 
원하는 키 이벤트를 필요한 클래스에서 구독하시면 해당 키 입력을 처리하실수있어요 
사용법 Sample 스크린샷
리뷰해주세요~
> [feat] InputManager 구현 #14

- Assets/Resources.meta
- Assets/Resources/BGM.meta
- Assets/Resources/SFX.meta
- Assets/Scripts/Singleton.cs
- Assets/Scripts/Singleton.cs.meta
- Assets/Scripts/SoundManager.cs
- Assets/Scripts/SoundManager.cs.meta
SoundManager.cs, Singleton.cs 및 Resources/SFX 와 Resources/BGM 폴더 제작
BGMType 및 SFXType은 공란
> [feat]SoundManager.cs 제작 및 리소스 특수폴더 생성

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
> Create issue template

- Assets/Blue.mat
- Assets/Blue.mat.meta
- Assets/Prefabs/Prototype/Player.prefab
- Assets/Prefabs/Prototype/Player.prefab.meta
- Assets/Scenes/Board.unity
- Assets/ScriptableObject/OnGameStart.asset
- Assets/ScriptableObject/OnGameStart.asset.meta
- Assets/ScriptableObject/OnRollDice.asset
- Assets/ScriptableObject/OnRollDice.asset.meta
- Assets/Scripts/Board.cs
- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Dice.cs
- Assets/Scripts/IntEventChannelSO.cs
- Assets/Scripts/IntEventChannelSO.cs.meta
- Assets/Scripts/Player.cs
- Assets/Scripts/Tile.cs
- Assets/Scripts/VoidEventChannelSO.cs
- Assets/Scripts/VoidEventChannelSO.cs.meta
>  #21 
> - 처음에 주사위 돌려서 순서 설정
> - 순서대로 주사위 던지고 그 값 만큼 이동
> - 턴 횟수 만큼 반복
> [feat] 보드게임 핵심 로직 구현

- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Dice.cs
- Assets/Scripts/Player.cs
- Assets/Scripts/SoundManager.cs
30-style-변수-함수명 수정하기
private 메소드에 _ 추가
기타 변수명 수정
> [style]변수/함수명 수정

- Assets/ScriptableObject/OnMainGameStarted.asset
- Assets/ScriptableObject/OnMainGameStarted.asset.meta
- Assets/ScriptableObject/OnRollButtonClicked.asset
- Assets/ScriptableObject/OnRollButtonClicked.asset.meta
- Assets/ScriptableObject/OnSetOrderRollDice.asset
- Assets/ScriptableObject/OnSetOrderRollDice.asset.meta
- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Dice.cs
- Assets/Scripts/GameUI.cs
- Assets/Scripts/GameUI.cs.meta
> #31
> BoardManager 변수명 수정 -> GameTurn, PlayerTurn 구분
주사위 버튼 입력 이벤트 처리
주사위 출력 이벤트 처리
턴 기반 게임 로직 수정
> **### 나중에 변수/메서드 이름 변경, 지워도 되는 주석 위주로 리뷰 해주세요!!**
> **### 코드 옆에 + 버튼 눌러서 커멘트 가능해요!**
>
> [feat] 입력 받아서 핵심 게임 로직 처리 #31

- Assets/MeowrioAsset/Animation/Dice.controller
- Assets/MeowrioAsset/Animation/Dice/Idle.anim
- Assets/MeowrioAsset/Animation/Dice/Idle.anim.meta
- Assets/Prefabs/Prototype/BlueDice.prefab
- Assets/Prefabs/Prototype/BlueDice.prefab.meta
- Assets/Prefabs/Prototype/Player.prefab
- Assets/Scenes/Board.unity
- Assets/Scenes/SampleScene.unity
- Assets/Scenes/TestScene.unity
- Assets/Scenes/TestScene.unity.meta
- Assets/Scripts/Board.cs
- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Dice.cs
- Assets/Scripts/GameUI.cs
- Assets/Scripts/Player.cs
- Assets/Scripts/PlayerHeadUI.cs
- Assets/Scripts/PlayerHeadUI.cs.meta
- Assets/Scripts/Tile.cs
- Assets/Scripts/VoidEventChannelSO.cs
- Assets/Scripts/hhwTest.meta
- Assets/Scripts/hhwTest/InputManagerTest.cs
- Assets/Scripts/hhwTest/InputManagerTest.cs.meta
> #33 #37
> 게임 핵심 로직 변경
* 프로젝트 전체에서 기존 로직에 쓰이던 이벤트 삭제
* [Board Manager] 게임 Phase 추가
* [Board Manager] 내부 로직 Update로 이동
* [Player] [Dice] 주사위 관련 로직 변경
추후 업로드
> BoardManager 내부 Update 메서드 중심으로 봐주시면 됩니다!
> [Refactor] 게임 메인 로직이 게임 프로세스를 명확하게 반영하도록 수정

- Assets/Prefabs/Prototype/UI.prefab
- Assets/Prefabs/Prototype/UI.prefab.meta
> ex) 49번 이슈 UI 디자인
NoticeUI, ButtonUI, RoundUI, LeaderBoardUI 제작했습니다
> [design]UI 프리팹 제작

- Assets/InputSystem_Actions.inputactions
- Assets/Scenes/Board.unity
- Assets/ScriptableObject/InputManagerSO.cs
- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Phase.cs
- Assets/Scripts/Phase.cs.meta
> #48 
> FSM 상태 패턴 적용
* 현재 게임의 상태를 Phase를 명칭으로 쓰기에 맞춰서 Phase, PhaseMachine으로 구현
> Input System 입력 적용
* 현재 방식 : BoardManager의 Update에서 키 입력 처리
* 변경 방식 : Input System의 키 입력 Event로 처리
※ 현재 순서를 정하는 주사위 키 입력을 Player에 따라 구분하게 되어 있는데 Netcode 멀티플레이 적용 시 사라질 코드입니다!
Update 내에 있던 키 입력 처리 로직들이 키 입력에 따른 이벤트 처리 함수들로 나눠진 걸 중점으로 봐주시면 될 것 같습니다!
> [Refactor] FSM 상태 패턴 적용하기 + InputSystem 입력 적용

- Assets/Prefabs/Prototype/Player.prefab
- Assets/Scenes/Board.unity
- Assets/ScriptableObject/InputManagerSO.cs
- Assets/Scripts/BoardManager.cs
- Assets/Scripts/Dice.cs
- Assets/Scripts/Player.cs
#59 
- 키보드 입력 받는 위치를 BoardManager -> Player로 수정
- 현재 netCode 적용 전이라 플레이어 별로 InputAction 생성해서 사용하는 방식은 유지 
- 플레이어 ID와 해당 액션은 Dictionary에 넣어서 관리하는 걸로 수정 
=> 네트워크 붙이면 단일 Action으로 처리하고 서버에서 이를 판단하게 수정하기
- BoardManager에서 현재 Phase에 맞는 로직 실행 및 현재 Turn인 플레이어인지 체크
현재 플레이어의 Turn이 진행 중인지 체크해주는 변수가 따로 있어야 할 것 같습니다. 키 반복 입력 시 동시에 움직이는 문제가 있습니다.
> [Refactor] 키보드 입력을 Player에서 받도록 수정

- Assets/Prefabs/Prototype/CameraManager.prefab
- Assets/Prefabs/Prototype/CameraManager.prefab.meta
- Assets/Prefabs/Prototype/VirtualCamera.prefab
- Assets/Prefabs/Prototype/VirtualCamera.prefab.meta
- Assets/Scripts/CameraManager.cs
- Assets/Scripts/CameraManager.cs.meta
> #42 
> CameraManager 구현 및 Prefab화, VirtualCamera Prefab화
기본적으로 Board 카메라, Player Focus 카메라, Player Move 카메라라는 프리셋을 미리 만들어두고
ChangeCamera 메서드를 타입에 따라 호출하면 해당 카메라를 On 할 수 있습니다!
프리셋 카메라 외에 원하는 각도의 Virtual Camera를 만들어 두고 VirtualCameraList에 추가, 
ChangeCamera 메서드를 index로 호출하면 해당 카메라를 On 시킬 수 있습니다!
https://github.com/user-attachments/assets/30767534-ee96-424e-9dc0-fd6b5cdd3f49
카메라 전환 효과는 조금 더 연구해볼게요
> [Feature] CameraManager 제작

- Assets/Scenes/ProtoTypeScene.unity
- Assets/Scripts/MiniGameManager.cs
- Assets/Scripts/MiniGameManager.cs.meta
> ex) #77 
> 미니게임을 싱글 버전으로 만들었습니다.
미니게임이 시작되면 지정된 위치로 플레이어가 이동하고 플레이어는 최저속도로 계속해서 전진합니다.
기본적으로 플레이어는 1 프레임마다 감속하고 키 연타를 통해 가속할 수 있습니다. 골인을 하면 플레이어는 이동을 멈추고 기존 위치로 돌아갑니다.
> [Feat]미니게임 제작

- Assets/DefaultNetworkPrefabs.asset
- Assets/Prefabs/NetworkTestPrefabs/NetMiniTestLuigi.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetMiniTestLuigi.prefab.meta
- Assets/Prefabs/NetworkTestPrefabs/NetMiniTestMario.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetMiniTestMario.prefab.meta
- Assets/Scenes/TapRaceScene.unity
- Assets/Scenes/TapRaceScene.unity.meta
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/MiniGameManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/MiniGamePlayerController.cs.meta
- Assets/UserChoices.choices
- ProjectSettings/EditorBuildSettings.asset
#78 
- 미니게임 멀티 플레이 가능하도록 수정
- 매 라운드가 끝나면 미니게임 진행 되도록 연결
- 미니게임은 Additive mode 로 load 되고, 끝나면 unload 되는 방식
- 메인 보드게임에서 접속한 순서대로 루이지, 마리오 지정해준 것처럼 미니게임에서도 순서대로 루이지, 마이로 프리팹 Instantiate 되게 했습니다. 나중에 수정할 수 있으면 좋을 것 같아요.
- 아래 2가지는 수정하면 좋을 것 같다고 느낀 부분들인데 어떻게 생각하시는지 의견 부탁드려요!
1. 미니게임 우승자 판단 방법 : 매번 거리 계산 => OnTrigger 충돌 감지
2.  미니게임 종료 판정 : PlayerController => Manager 가 BoardManager 에게 끝났다고 알리기
> [Feat] 미니게임 네트워크 적용 및 메인 게임과 연결

- Assets/Resources/UI/LeaderBoardUI.prefab
- Assets/Scenes/Board.unity
- Assets/Scripts/Controller/TileController.cs
- Assets/Scripts/Data/PlayerData.cs
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/LeaderBoardManager.cs
- Assets/Scripts/Managers/LeaderBoardManager.cs.meta
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/UI/BaseUI.cs
- Assets/Scripts/UI/LeaderBoardUI.cs
- Assets/Scripts/UI/UIManager.cs
#62 
- 게임 흐름에 맞게 데이터 반영해서 UI 팝업 시스템 추가
- UI Manager 에 상황에 맞게 쓸 수 있도록 함수 여러 개 제작
- 코인 개수로 순위 컨트롤 하여서 ui 로 보여주는 LeaderBoardManager 를 추가했습니다. 이건 서버에서만 존재해요. 사용할 때 참고해주세요!
[구현된 내용]
순서 정해보죠 팝업 표시(모두) <n초뒤>팝업 사라짐(모두) ✔️
~ 라운드 시작! 팝업(모두) <n초 뒤>팝업 사라짐(모두) ✔️
주사위 굴리라는 팝업_**(해당 차례인 사람만❌)**_
<주사위 굴리면>팝업 사라짐 ✔️
<라운드 종료>
미니게임 시작! + 간단한 게임 설명(모두)✔️
<미니게임 종료>우승자는 ###! 팝업 (모두) ✔️
코인 획득 반영한 리더보드 팝업(모두)  n초뒤 사라지고 ✔️
일단 구현되게 하는 거에 포커스 두고 만들어서 호출 순서 같은 거는 나중에 깔끔하게 다듬어야 할 것 같습니다. 
UIManager 에서 함수 여러 개 만든 것도 괜찮은 방법인지.. 모르겠어요 ㅜㅜ 
클라이언트 별로 다른 메세지 보내는 기능 추가(주사위 굴리라고 할 때)
미니게임 끝나면 누가 이겼는지 id 정보 넘기는데 제대로 안 넘어감
---
리더보드에 넣을 이미지 필요
> [Feat] UI System 적용

- Assets/Prefabs/Prototype/CameraManager.prefab
- Assets/Scenes/Board.unity
- Assets/Scenes/LobbyScene.unity
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/CameraManager.cs
- Assets/Scripts/Managers/SoundManager.cs
- Assets/Scripts/Singleton.cs
- Assets/Scripts/UI/UIManager.cs
- ProjectSettings/EditorBuildSettings.asset
> ex) #이슈번호, #이슈번호
코드 정리
앞으로 할일
> 싱글턴 정리
> 가급적 인스펙터 상에서 할당
> 92 feat 로비 씬과 게임 씬 연결

- Assets/MeowrioAsset/Animation/Dice.controller
- Assets/MeowrioAsset/Animation/Dice/DiceRolling.anim
- Assets/Prefabs/BoardManager.prefab
- Assets/Prefabs/CameraManager.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetTestLuigi.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetTestMario.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetworkManager.prefab
- Assets/Scenes/TapRaceScene.unity
- Assets/Scripts/Controller/DiceController.cs
- Assets/Scripts/Controller/PlayerController.cs
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/CameraManager.cs
- Assets/Scripts/MiniGameManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/TapRaceScene.cs
> #81
> 카메라 전환 등 전반적인 연출 부분 구현 및 수정
* player 숫자 안꺼지는 현상 수정
* 순서 설정 완료 연출
* 주사위 애니메이션 동작
* 미니게임 카메라 전환
* 보드게임 턴 진행 간 연출
> 81 feature 카메라 연출 적용

- Assets/Scripts/MiniGameManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/TapRaceScene.cs
> 
> PlayerObject null 되는 현상 + 두번째 미니게임 MinigameManager 인스턴싱 안되는 현상 수정
> [fix] PlayerObject null 되는 현상 + 두번째 미니게임 MinigameManager 인스턴싱 안되는 현상 수정

- Assets/Resources/UI/ExchangeStarUI.prefab
- Assets/Resources/UI/NoticeUI.prefab
- Assets/Scenes/BoardTest.unity
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/LeaderBoardManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/UI/BaseUI.cs
- Assets/Scripts/UI/UIManager.cs
- ScoreBoard Sorting 되며 인덱스 바뀌는 문제 수정
- 리더보드 팝업이 계속 되는 문제 수정
- 우승자 이름 출력
> [Fix] ScoreBoard 인덱스, 리더보드 팝업

- Assets/Prefabs/BoardManager.prefab
- Assets/Prefabs/NetworkTestPrefabs/BirdoMiniGame.prefab
- Assets/Prefabs/NetworkTestPrefabs/LuigiMiniGame.prefab
- Assets/Prefabs/NetworkTestPrefabs/MarioMiniGame.prefab
- Assets/Prefabs/NetworkTestPrefabs/WaluigiMiniGame.prefab
- Assets/Prefabs/Prototype/LeaderboardManager.prefab
- Assets/Prefabs/Prototype/UIManager.prefab
- Assets/Scenes/BoardTest.unity
- Assets/ScriptableObject/DataSO.asset
- Assets/ScriptableObject/DataSO.asset.meta
- Assets/ScriptableObject/DataSO.cs
- Assets/ScriptableObject/DataSO.cs.meta
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/LeaderBoardManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
- Assets/Scripts/UI/UIManager.cs
#111 
- 스타 구매 시 해당 턴인 사람에게만 구매 창 팝업, 구매 후 결과 동기화
- Scriptable OBject 로 코인, 스타 개수 관리
> [Bug] 코인, 스타 개수 동기화 문제

- Assets/MeowrioAsset/Animation/Player.controller
- Assets/MeowrioAsset/Animation/Player/birdoAni/Walk.anim
- Assets/MeowrioAsset/Animation/Player/waluigiAni/Idle.anim
- Assets/MeowrioAsset/Animation/Player/waluigiAni/Walk.anim
- Assets/MeowrioAsset/Animation/PlayerBirdo.controller
- Assets/MeowrioAsset/Animation/PlayerWaluigi.controller
- Assets/Prefabs/NetworkTestPrefabs/Birdo.prefab
- Assets/Prefabs/NetworkTestPrefabs/Luigi.prefab
- Assets/Prefabs/NetworkTestPrefabs/Mario.prefab
- Assets/Prefabs/NetworkTestPrefabs/NetworkManager.prefab
- Assets/Prefabs/NetworkTestPrefabs/Waluigi.prefab
- Assets/ScriptableObject/DataSO.cs
- Assets/Scripts/Controller/PlayerController.cs
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/Managers/LeaderBoardManager.cs
- Assets/Scripts/UI/LobbyUI.cs
- Assets/Scripts/UI/UIManager.cs
> 
> 3p 4p 프리팹 수정 + 스타 교환 UI 멈추고 다시 진행
> [fix] 3p 4p 프리팹 수정 + 스타 교환 UI 멈추고 다시 진행

- Assets/MeowrioAsset/Animation/Star.controller
- Assets/MeowrioAsset/Item/Star/Goal Star.prefab
- Assets/Prefabs/NetworkTestPrefabs/Birdo.prefab
- Assets/Prefabs/NetworkTestPrefabs/Luigi.prefab
- Assets/Prefabs/NetworkTestPrefabs/Mario.prefab
- Assets/Prefabs/NetworkTestPrefabs/Waluigi.prefab
- Assets/Scenes/BoardTest.unity
- Assets/Scripts/Controller/PlayerController.cs
- Assets/Scripts/Controller/TileController.cs
- Assets/Scripts/Managers/BoardManager.cs
- Assets/Scripts/MiniGamePlayerController.cs
> [Feat] 코인 증감 ui 추가
